name: Smoketest Twitch Selectors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC

permissions:
  contents: write
  issues: write

jobs:
  smoketest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check download response headers
        run: curl -I https://raw.githubusercontent.com/adjstreams/twitch-user-notes/baselines/last-smoketest.json || echo "Failed to fetch headers"

      - name: Download baseline from baselines branch
        run: |
          curl -s -o .github/smoketest/last-smoketest.json \
            https://raw.githubusercontent.com/adjstreams/twitch-user-notes/baselines/last-smoketest.json || \
            echo "{}" > .github/smoketest/last-smoketest.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Selector Smoketest
        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' npm run smoketest

      - name: Upload new baseline to baselines branch
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git fetch origin baselines || git checkout --orphan baselines
          git switch baselines || git checkout -b baselines
          cp .github/smoketest/last-smoketest.json .
          git add last-smoketest.json
          git commit -m "Update baseline from CI run" || echo "No changes to commit"
          git push -f origin baselines

      - name: Create GitHub Issue on Selector Drop
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Twitch DOM Change Detected
          content-filepath: .github/smoketest/alert.md
          labels: bug, smoketest
